package com.colligendis.server.database;

public enum ExecutionStatus {
	ERROR,
	UNKNOWN,
	RELATIONSHIP_WAS_CREATED, RELATIONSHIP_IS_EXISTS, RELATIONSHIP_IS_NOT_EXISTS, RELATIONSHIP_WAS_DELETED,
	MORE_THAN_ONE_RELATIONSHIP_IS_FOUND,
	NODE_WAS_CREATED, NODE_NOT_CREATED,
	NODE_IS_EXISTS, NODE_IS_NOT_EXISTS, MORE_THAN_ONE_NODE_IS_FOUND,
	NODE_WAS_DELETED, NODE_IS_NOT_DELETED,
	NODE_IS_FOUND, NODE_IS_NOT_FOUND, NODE_NOTHING_TO_UPDATE, NODE_WAS_UPDATED
}