#!/usr/bin/env python3
"""Generate NumistaGradingDesignation.java from per-service option lists."""

import re
from pathlib import Path

# service numista value -> list of (value, label)
DESIGNATIONS_BY_SERVICE: dict[str, list[tuple[str, str]]] = {
    "8": [  # ANACS
        ("846", "5 STEPS"),
        ("847", "5.5 STEPS"),
        ("848", "6 STEPS"),
        ("854", "BRN"),
        ("844", "CAMEO"),
        ("851", "DCAM"),
        ("814", "DETAILS"),
        ("845", "DMPL"),
        ("850", "FBL"),
        ("849", "FH"),
        ("857", "FSB"),
        ("856", "PL"),
        ("855", "RB"),
        ("853", "RED"),
        ("858", "UDM"),
    ],
    "5": [  # CAC
        ("218", "+"),
        ("371", "Advanced Delivery"),
        ("360", "BN"),
        ("221", "CA"),
        ("222", "CAM"),
        ("362", "DCAM"),
        ("364", "DMPL"),
        ("366", "FB"),
        ("368", "FBL"),
        ("367", "FH"),
        ("370", "First Day of Delivery"),
        ("369", "First Delivery"),
        ("365", "FS"),
        ("436", "Mint Error"),
        ("363", "PL"),
        ("220", "QR"),
        ("361", "RB"),
        ("219", "RD"),
    ],
    "9": [  # GENI
        ("920", "+"),
        ("916", "Cleaning"),
        ("917", "Damage"),
        ("919", "Envt Damage"),
        ("938", "Filed rims"),
        ("931", "Graffiti"),
        ("918", "Scratch"),
    ],
    "10": [  # ICG
        ("945", "BN"),
        ("940", "CAM"),
        ("941", "DCAM"),
        ("942", "Details"),
        ("939", "PL"),
        ("944", "RB"),
        ("943", "RD"),
    ],
    "1": [  # NGC
        ("419", "+"),
        ("420", "★"),
        ("296", "5FS"),
        ("295", "5FS DPL"),
        ("297", "5FS PL"),
        ("299", "6FS"),
        ("298", "6FS DPL"),
        ("300", "6FS PL"),
        ("301", "BN"),
        ("302", "BN BRILLIANT"),
        ("303", "BN CAMEO"),
        ("304", "BN DPL"),
        ("305", "BN MATTE"),
        ("306", "BN PL"),
        ("307", "BN SATIN"),
        ("308", "BN ULTRA CAMEO"),
        ("309", "CAMEO"),
        ("312", "DPL"),
        ("314", "DPL ENHANCED FINISH"),
        ("323", "DPL FIRST DAY OF ISSUE"),
        ("310", "DPL FIRST DAY OF MINTAGE"),
        ("311", "DPL MINT ERROR"),
        ("313", "ENHANCED FINISH"),
        ("316", "ENHANCED REV PF"),
        ("318", "FB"),
        ("319", "FB DPL"),
        ("321", "FB PL"),
        ("320", "FBL"),
        ("328", "FBL DPL"),
        ("329", "FBL PL"),
        ("325", "FH"),
        ("326", "FH DPL"),
        ("327", "FH PL"),
        ("322", "FIRST DAY OF ISSUE"),
        ("330", "FIRST DAY OF MINTAGE"),
        ("331", "FT"),
        ("332", "FT DPL"),
        ("333", "FT PL"),
        ("334", "MATTE"),
        ("335", "MINT ERROR"),
        ("337", "PL"),
        ("315", "PL ENHANCED FINISH"),
        ("324", "PL FIRST DAY OF ISSUE"),
        ("336", "PL FIRST DAY OF MINTAGE"),
        ("338", "PL MINT ERROR"),
        ("339", "RB"),
        ("340", "RB BRILLIANT"),
        ("341", "RB CAMEO"),
        ("342", "RB DPL"),
        ("343", "RB MATTE"),
        ("344", "RB PL"),
        ("345", "RB SATIN"),
        ("346", "RB ULTRA CAMEO"),
        ("347", "RD"),
        ("348", "RD BRILLIANT"),
        ("349", "RD CAMEO"),
        ("350", "RD DPL"),
        ("355", "RD FIRST DAY OF ISSUE"),
        ("351", "RD MATTE"),
        ("352", "RD PL"),
        ("357", "RD RELEASE CEREMONY"),
        ("353", "RD SATIN"),
        ("354", "RD ULTRA CAMEO"),
        ("356", "RELEASE CEREMONY"),
        ("358", "SATIN"),
        ("317", "UC ENHANCED FINISH"),
        ("359", "ULTRA CAMEO"),
    ],
    "2": [  # NGC Ancient
        ("192", "★"),
        ("193", "fine style"),
        ("194", "marks"),
    ],
    "7": [  # NGCX
        ("631", "+"),
        ("632", "★"),
        ("547", "5FS"),
        ("546", "5FS DPL"),
        ("548", "5FS PL"),
        ("550", "6FS"),
        ("549", "6FS DPL"),
        ("551", "6FS PL"),
        ("552", "BN"),
        ("553", "BN BRILLIANT"),
        ("554", "BN CAMEO"),
        ("555", "BN DPL"),
        ("556", "BN MATTE"),
        ("557", "BN PL"),
        ("558", "BN SATIN"),
        ("559", "BN ULTRA CAMEO"),
        ("560", "CAMEO"),
        ("563", "DPL"),
        ("565", "DPL ENHANCED FINISH"),
        ("574", "DPL FIRST DAY OF ISSUE"),
        ("561", "DPL FIRST DAY OF MINTAGE"),
        ("562", "DPL MINT ERROR"),
        ("564", "ENHANCED FINISH"),
        ("567", "ENHANCED REV PF"),
        ("569", "FB"),
        ("570", "FB DPL"),
        ("572", "FB PL"),
        ("571", "FBL"),
        ("579", "FBL DPL"),
        ("580", "FBL PL"),
        ("576", "FH"),
        ("577", "FH DPL"),
        ("578", "FH PL"),
        ("573", "FIRST DAY OF ISSUE"),
        ("581", "FIRST DAY OF MINTAGE"),
        ("582", "FT"),
        ("583", "FT DPL"),
        ("584", "FT PL"),
        ("585", "MATTE"),
        ("586", "MINT ERROR"),
        ("588", "PL"),
        ("566", "PL ENHANCED FINISH"),
        ("575", "PL FIRST DAY OF ISSUE"),
        ("587", "PL FIRST DAY OF MINTAGE"),
        ("589", "PL MINT ERROR"),
        ("590", "RB"),
        ("591", "RB BRILLIANT"),
        ("592", "RB CAMEO"),
        ("593", "RB DPL"),
        ("594", "RB MATTE"),
        ("595", "RB PL"),
        ("596", "RB SATIN"),
        ("597", "RB ULTRA CAMEO"),
        ("598", "RD"),
        ("599", "RD BRILLIANT"),
        ("600", "RD CAMEO"),
        ("601", "RD DPL"),
        ("606", "RD FIRST DAY OF ISSUE"),
        ("602", "RD MATTE"),
        ("603", "RD PL"),
        ("608", "RD RELEASE CEREMONY"),
        ("604", "RD SATIN"),
        ("605", "RD ULTRA CAMEO"),
        ("607", "RELEASE CEREMONY"),
        ("609", "SATIN"),
        ("568", "UC ENHANCED FINISH"),
        ("610", "ULTRA CAMEO"),
    ],
    "3": [  # PCGS
        ("437", "+"),
        ("766", "BM"),
        ("767", "BMCA"),
        ("102", "BN"),
        ("103", "CAM"),
        ("104", "DCAM"),
        ("422", "DM"),
        ("765", "DMPL"),
        ("762", "FB"),
        ("764", "FBL"),
        ("763", "FH"),
        ("768", "First Strike"),
        ("761", "FS"),
        ("435", "Mint Error"),
        ("421", "PL"),
        ("101", "RB"),
        ("100", "RD"),
        ("769", "Satin Finish"),
        ("770", "SMS"),
        ("105", "SP"),
    ],
    "6": [  # PCGS Banknote
        ("470", "DETAILS"),
        ("472", "First Day of Issue"),
        ("471", "FirstPrint"),
        ("467", "OPQ"),
        ("466", "PPQ"),
    ],
    "4": [  # PMG
        ("106", "★"),
        ("107", "EPQ"),
        ("108", "NET"),
    ],
}

SERVICE_PREFIX = {
    "1": "NGC",
    "2": "NGC_ANCIENT",
    "3": "PCGS",
    "4": "PMG",
    "5": "CAC",
    "6": "PCGS_BANKNOTE",
    "7": "NGCX",
    "8": "ANACS",
    "9": "GENI",
    "10": "ICG",
}


def java_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace("\"", "\\\"")


def to_enum_name(prefix: str, value: str, label: str, used: set[str]) -> str:
    base = re.sub(r"[^A-Za-z0-9]+", "_", label.upper()).strip("_")
    if not base:
        base = "DESIGNATION"
    if base[0].isdigit():
        base = "D_" + base
    name = f"{prefix}_{base}"
    if name in used:
        name = f"{name}_V{value}"
    used.add(name)
    return name


def main() -> None:
    entries: list[tuple[str, str, str, str]] = []
    used_names: set[str] = set()

    for service_id in ("1", "2", "3", "4", "5", "6", "7", "8", "9", "10"):
        prefix = SERVICE_PREFIX[service_id]
        for value, label in DESIGNATIONS_BY_SERVICE[service_id]:
            enum_name = to_enum_name(prefix, value, label, used_names)
            entries.append((enum_name, value, service_id, label))

    entries.sort(key=lambda e: (int(e[1]), e[2], e[3]))

    out = (
        Path(__file__).parent.parent
        / "src/main/java/com/colligendis/server/parser/numista/collection/NumistaGradingDesignation.java"
    )
    lines = [
        "package com.colligendis.server.parser.numista.collection;",
        "",
        "import java.util.Arrays;",
        "import java.util.List;",
        "import java.util.Optional;",
        "",
        "import org.springframework.util.StringUtils;",
        "",
        "/**",
        " * Values for Numista {@code collec_form_grading_designation} / {@code gradingDesignation[]}.",
        " * Options depend on {@link NumistaGradingService} ({@link #serviceId}).",
        " */",
        "public enum NumistaGradingDesignation {",
    ]

    for i, (enum_name, value, service_id, label) in enumerate(entries):
        comma = "," if i < len(entries) - 1 else ";"
        lines.append(
            f'\t{enum_name}("{value}", "{service_id}", "{java_escape(label)}"){comma}'
        )

    lines.extend(
        [
            "",
            "\tprivate final String numistaValue;",
            "\tprivate final String serviceId;",
            "\tprivate final String label;",
            "",
            "\tNumistaGradingDesignation(String numistaValue, String serviceId, String label) {",
            "\t\tthis.numistaValue = numistaValue;",
            "\t\tthis.serviceId = serviceId;",
            "\t\tthis.label = label;",
            "\t}",
            "",
            "\tpublic String getNumistaValue() {",
            "\t\treturn numistaValue;",
            "\t}",
            "",
            "\t/** {@link NumistaGradingService} numista value. */",
            "\tpublic String getServiceId() {",
            "\t\treturn serviceId;",
            "\t}",
            "",
            "\tpublic String getLabel() {",
            "\t\treturn label;",
            "\t}",
            "",
            "\tpublic Optional<NumistaGradingService> getGradingService() {",
            "\t\treturn NumistaGradingService.fromNumistaValue(serviceId);",
            "\t}",
            "",
            "\tpublic static Optional<NumistaGradingDesignation> fromNumistaValue(String value) {",
            "\t\tif (!StringUtils.hasText(value)) {",
            "\t\t\treturn Optional.empty();",
            "\t\t}",
            "\t\tString trimmed = value.trim();",
            "\t\treturn Arrays.stream(values())",
            "\t\t\t\t.filter(d -> d.numistaValue.equals(trimmed))",
            "\t\t\t\t.findFirst();",
            "\t}",
            "",
            "\tpublic static Optional<NumistaGradingDesignation> fromNumistaValueAndService(",
            "\t\t\tString value, NumistaGradingService gradingService) {",
            "\t\tif (!StringUtils.hasText(value) || gradingService == null) {",
            "\t\t\treturn Optional.empty();",
            "\t\t}",
            "\t\tString trimmed = value.trim();",
            "\t\tString serviceValue = gradingService.getNumistaValue();",
            "\t\treturn Arrays.stream(values())",
            "\t\t\t\t.filter(d -> d.numistaValue.equals(trimmed) && d.serviceId.equals(serviceValue))",
            "\t\t\t\t.findFirst();",
            "\t}",
            "",
            "\tpublic static List<NumistaGradingDesignation> forService(NumistaGradingService gradingService) {",
            "\t\tif (gradingService == null) {",
            "\t\t\treturn List.of();",
            "\t\t}",
            "\t\tString serviceValue = gradingService.getNumistaValue();",
            "\t\treturn Arrays.stream(values())",
            "\t\t\t\t.filter(d -> d.serviceId.equals(serviceValue))",
            "\t\t\t\t.toList();",
            "\t}",
            "",
            "\tpublic static Optional<NumistaGradingDesignation> fromLabelAndService(",
            "\t\t\tString label, NumistaGradingService gradingService) {",
            "\t\tif (!StringUtils.hasText(label) || gradingService == null) {",
            "\t\t\treturn Optional.empty();",
            "\t\t}",
            "\t\tString trimmed = label.trim();",
            "\t\tString serviceValue = gradingService.getNumistaValue();",
            "\t\treturn Arrays.stream(values())",
            "\t\t\t\t.filter(d -> d.serviceId.equals(serviceValue) && d.label.equalsIgnoreCase(trimmed))",
            "\t\t\t\t.findFirst();",
            "\t}",
            "}",
            "",
        ]
    )

    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(entries)} designations to {out}")


if __name__ == "__main__":
    main()
